### ISSUE TITLE
installs on linux mint 18.1 but doesn't start

### ISSUE THREAD

**Issue by duck7000** [PhotoFiltre-LX/photofiltrelx#20]
I installed it on mint, all dependencies are good according to the installer but the program doesn't start at all.
I know it state ubuntu but mint is based on ubuntu lts 16.04, so i thought it would work.

How can i get this program working?

Edit: I used the 64bit deb file, double click on it and installed it. All dependencies are for filled it states.
Shortcut is made in the menu but if you click on it nothing happens.
I tried the 32bit version also, same result.
Tried to build it with qt creator but got a configuration error

**Comment by duck7000** [comment]
Does it only work with ubuntu 16.10 then?

**Comment by Dean-Coakley** [comment]
In my experience it will run on Ubuntu 16.04 with a few issues. Typically issues are just with performance.

It runs best on 16.10.

What configuration error did you get?

**Comment by DylanC** [comment]
Apologies for the late reply. The latest version of the image editor only works on lib Qt 5.6. Ubuntu 16.04 does not have this version of Qt, so the current version only works on 16.10+.

I may possibly build a version for Mint soon but only if I have the time.

**Comment by duck7000** [comment]
Okay i understand, thanks for explaining.

I am new to linux so i have to learn al lot

Is there perhaps a older version that does run on linuxmint (ubuntu lts 16.04 based)?

If not i guess i'll have to wait then

qt creator gives fault about missing kit to build and kit desktop is invalid

**Comment by duck7000** [comment]
I have found instructions to install qt 5.6.1 on ubuntu derivatives, this went well.
But after install of photofiltreLX....  it still won't start

Just for your information
http://sourcedigit.com/19858-how-to-install-qt-5-6-1-on-ubuntu-16-04/

**Comment by DylanC** [comment]
Don't worry, I am working on a proper Mint .deb at the moment.

**Comment by duck7000** [comment]
Okay Thanks!

**Comment by DylanC** [comment]
Please check the latest blog post. I created an installer for Mint now.  Please note there is a bug with painting on 16.04 but this is an issue with Qt, so we cannot fix it.  

To have a better experience you would need to use a newer version of Ubuntu. (16.10 or 17.04)
