### ISSUE TITLE
Major painting performance issue on Linux

### ISSUE THREAD

**Issue by Dean-Coakley** [PhotoFiltre-LX/photofiltrelx#3]

**Comment by Dean-Coakley** [comment]
Not an issue on the latest version of Qt. We will likely just port the project to this version as soon as possible because it is a LTS version.

**Comment by DylanC** [comment]
Yeah its in the pipeline to set a standard Qt version to build upon. Qt5.5 has the bug Qt5.6 does not and it an LTS version.
